# Site settings
title: Fabian's digital home
email: fabian@schwarz-fritz.de
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my digital home. This is my blog and website and space other things. What people called a personal website back in the days. It's mainly about software development, projects, me, or sometimes maybe a bit philosophical. I don't only writing because I find the content interesting, or to have "my own cool blog that no one will read", but mostly to improve my writing style. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fabianschwarzfritz.github.io" # the base hostname & protocol for your site
github_username:  fabianschwarzfritz

# Build settings
markdown: kramdown
