name: Fabian Schwarz-Fritz
description: Thoughts, impressions, ideas.
meta_description: "Thoughts I have. Impressions I get. Ideas I spread."

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://fabianschwarzfritz.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://fabianschwarzfritz.github.io'
author:         'Fabian Schwarz-Fritz'
# authorTwitter:  ''

permalink:       /:year-:month-:day/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
